Ian's code change done on Meraj's files
pyroib/ITC205-G7 pull request #39
Opened 2018-08-15 07:58 UTC by pyroib

I have done an initial code change in Meraj's files. This will need a review before merging

2018-08-15 11:54 UTC, jazzie-b requested changes
Some additional changes may be require. See comments on review. Each comment has associated issue number attached.

2018-08-15 11:54 UTC, jazzie-b commented on src/FixBookUi.java
> +    public void setState(UiState state) {
Might want to change setState to setUiState to match variable name change, see #32

2018-08-15 11:54 UTC, jazzie-b commented on src/FixBookUi.java
> +    public void run() {
Could use a more meaningful variable name, as requested. See #32

2018-08-15 11:54 UTC, jazzie-b commented on src/FixBookUi.java
> +        System.out.println(object);
Interesting change, very much valid.

2018-08-15 11:54 UTC, jazzie-b commented on src/FixBookUi.java
> +                    if (uppercaseAnswer.equals("Y")) {
Still a method within method call, could be substituted using a boolean. See issue #32

2018-08-15 11:54 UTC, jazzie-b commented on src/Loan.java
> +    public void dischargeLoan() {
Not requested, but valid method name change

2018-08-15 11:54 UTC, jazzie-b commented on src/Loan.java
> +    public String toString() {
Method name ok, ignore request to change

2018-08-15 11:54 UTC, jazzie-b commented on src/Main.java
> +            int days = Integer.valueOf(userInput("Enter number of days: ")).intValue();
Still possibly a method within method call here, was requested to be looked. See #28

2018-08-15 11:54 UTC, jazzie-b commented on src/Main.java
> +            printOutput(simpleDateFormat.format(calender.setDate()));
Another possible method with in method call, uncorrected. See #28

2018-08-15 11:54 UTC, jazzie-b commented on src/PayFineUi.java
> +    private Scanner input;
Variable name could be more meaningful as requested, see #30

2018-08-16 02:04 UTC, pyroib commented on src/FixBookUi.java
> +    public void setState(UiState state) {
done

2018-08-16 02:05 UTC, pyroib commented on src/FixBookUi.java
> +    public void run() {
done: runFixBookUi

2018-08-16 02:52 UTC, pyroib commented
changes made. hopefully i got em all.

2018-08-16 13:07 UTC, jazzie-b reviewed
Might want to look at this one change. This branch is also going to need to be de-conflicted before merging.

2018-08-16 13:07 UTC, jazzie-b commented on src/Main.java
> +            String currentDate = simpleDateFormat.format(calender.setDate());
Still possible method within method call.

2018-08-16 15:06 UTC, jazzie-b commented
Branch has been deconflicted, one change still need to be made.

2018-08-16 23:44 UTC, pyroib commented
that is now done. i found the same thing on line 36, changed that too

2018-08-17 02:26 UTC, jazzie-b approved these changes
All changes have been made. Approved to merge.

2018-08-17 02:59 UTC, merged